version = 1

exclude_patterns = ["/dist"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "es-modules"
  ecma_version = "2019"
  environment = [
    "nodejs",
    "jest",
    "browser"
  ]
  plugins = ["react"]
  style_guide = "airbnb"
